version: "3.9"

services:
  mysqldb:
    image: mysql
    container_name: mysql-container
    environment: 
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: agenda-petshop
    ports: 
      - "3306:3306"
    networks: 
      - my-network
    volumes: 
      - "./app/infraestrutura/dbdata/:/var/lib/mysql"

  node-app:
    build: 
      context: .
      dockerfile: my-node.dockerfile
    image: henriquechav/my-nodejs
    depends_on: 
      - mysqldb
    container_name: node-container
    ports:
      - "3000:3000"
    networks:
      - my-network
    volumes: 
      - "./app/:/usr/app"

networks:
  my-network:
    driver: bridge